path=(~/bin $path)

export TERM=xterm
export EDITOR=$HOME/bin/EDITOR
export TIME_STYLE="long-iso"
export CONFIG_DIR=$HOME/.config

export XDG_CONFIG_HOME=$CONFIG_DIR
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

if [ -f $ZDOTDIR/zshenv_local ]; then
  source $ZDOTDIR/zshenv_local
fi 

export LESSHISTFILE=/dev/null
export PSQL_HISTORY=$XDG_STATE_HOME/psql_history

# only in rootless mode
# export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker

export ICEAUTHORITY=$XDG_CACHE_HOME/ICEauthority

export GITLIBS=$XDG_CACHE_HOME/clojure-gitlibs
